// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: other/protos/AllergenService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AllergenService {

  /// <summary>Holder for reflection information generated from other/protos/AllergenService.proto</summary>
  public static partial class AllergenServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for other/protos/AllergenService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AllergenServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJvdGhlci9wcm90b3MvQWxsZXJnZW5TZXJ2aWNlLnByb3RvEg9BbGxlcmdl",
            "blNlcnZpY2UaI290aGVyL3Byb3Rvcy9BbGxlcmdlbk1lc3NhZ2VzLnByb3Rv",
            "MoYDCg9BbGxlcmdlblNlcnZpY2USPwoDR2V0EhwuQWxsZXJnZW5NZXNzYWdl",
            "cy5HZXRSZXF1ZXN0GhouQWxsZXJnZW5NZXNzYWdlcy5BbGxlcmdlbhJLCgZH",
            "ZXRBbGwSHy5BbGxlcmdlbk1lc3NhZ2VzLkdldEFsbFJlcXVlc3QaIC5BbGxl",
            "cmdlbk1lc3NhZ2VzLkdldEFsbFJlc3BvbnNlEksKBkNyZWF0ZRIfLkFsbGVy",
            "Z2VuTWVzc2FnZXMuQ3JlYXRlUmVxdWVzdBogLkFsbGVyZ2VuTWVzc2FnZXMu",
            "Q3JlYXRlUmVzcG9uc2USSwoGVXBkYXRlEh8uQWxsZXJnZW5NZXNzYWdlcy5V",
            "cGRhdGVSZXF1ZXN0GiAuQWxsZXJnZW5NZXNzYWdlcy5VcGRhdGVSZXNwb25z",
            "ZRJLCgZEZWxldGUSHy5BbGxlcmdlbk1lc3NhZ2VzLkRlbGV0ZVJlcXVlc3Qa",
            "IC5BbGxlcmdlbk1lc3NhZ2VzLkRlbGV0ZVJlc3BvbnNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AllergenMessages.AllergenMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
