trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  isCsharpRepository: $[contains(variables['Build.Repository.Name'], 'repo')]

steps:
  - task: PowerShell@2
    condition: eq(variables.isCsharpRepository, true)
    inputs:
      filePath: 'build-nuget.ps1'



