trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

container: ubuntu-latest

variables:
  repositoryName: $(Build.Repository.Name)

steps:
  - task: PowerShell@2
    condition: contains(repositoryName, 'repo')
    inputs:
      filePath: 'build-nuget.ps1'



