trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: PowerShell@2
    condition: contains(variables['Build.Repository.Name'], 'repo')
    inputs:
      filePath: .\build-nuget.ps1
      arguments: >
        -input1 $(Build.Repository.Name)
        



