trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: PowerShell@2
    condition: contains($(Build.Repository.Name), 'repo')
    inputs:
      filePath: $(System.DefaultWorkingDirectory)\build-nuget.ps1
      arguments:  >
        -input1 $(Build.Repository.Name)
        



