trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables: 
  nugetShellScript: '$(Build.SourcesDirectory)/build-nuget.ps1'

steps:
  - task: PowerShell@2
    condition: contains(variables['Build.Repository.Name'], 'repo')
    inputs:
      filePath: $(nugetShellScript)



